---
- name: Check if rbenv is already installed
  stat:
    path: "{{ ansible_user_home_dir }}/.rbenv"
  register: check_rbenv_installation

- name: Check if rbenv is already installed
  stat:
    path: "{{ ansible_user_home_dir }}/.rbenv/plugins/ruby-build"
  register: check_ruby_build_installation

- name: Download rbenv
  command: "git clone https://github.com/rbenv/rbenv.git {{ ansible_user_home_dir }}/.rbenv"
  when: check_rbenv_installation.stat.exists == False

- name: Download ruby-build
  command: "git clone https://github.com/rbenv/ruby-build.git {{ ansible_user_home_dir }}/.rbenv/plugins/ruby-build"
  when: check_ruby_build_installation.stat.exists == False

- name: Skip ruby docs
  template:
    src: templates/gemrc
    dest: "{{ ansible_user_home_dir }}/.gemrc"

- name: append rbenv config to bash_profile
  become: yes
  template:
    src: templates/bash_profile
    dest: "~/.bash_profile"

- name: set rbenv permissions
  file:
    path: "{{ ansible_user_home_dir }}/.rbenv"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: install ruby 2.3.0
  command: "rbenv install 2.3.0"
  register: ruby_installed

- name: set rbenv global to 2.3.0 && install bundler
  command: "rbenv global 2.3.0 && gem install bundler"
  when: ruby_installed|succeeded

# - name: Install bundler
#   become_user: "{{ ansible_user }}"
#   command: bash -lc "gem install bundler"