---
- name: Check if rbenv is already installed
  stat:
    path: "{{ ansible_user_home_dir }}/.rbenv"
  register: check_rbenv_installation

- name: Check if rbenv is already installed
  stat:
    path: "{{ ansible_user_home_dir }}/.rbenv/plugins/ruby-build"
  register: check_ruby_build_installation

- name: Download rbenv
  command: "git clone https://github.com/rbenv/rbenv.git {{ ansible_user_home_dir }}/.rbenv"
  when: check_rbenv_installation.stat.exists == False

- name: Download ruby-build
  command: "git clone https://github.com/rbenv/ruby-build.git {{ ansible_user_home_dir }}/.rbenv/plugins/ruby-build"
  when: check_ruby_build_installation.stat.exists == False