---
- name: apt upgrade and update
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - git-core
    - build-essential
    - curl
    - fail2ban
    - nodejs
    - autoconf
    - bison
    - sqlite3
    - libcurl4-openssl-dev
    - libv8-dev
    - libpq-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
