---
- name: Install required packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-contrib

- name: Ensure DB user has access to the DB
  postgresql_user:
    name: "{{ ansible_user }}"
    password: "{{ postgresql_password }}"
    state: present
    role_attr_flags: SUPERUSER
  become: yes
  become_user: postgres

- name: Create DB
  postgresql_db:
    name: "{{ postgresql_db }}"
    owner: "{{ ansible_user }}"
  become: yes
  become_user: postgres

- name: Edit pg_hba.conf
  template:
    src: templates/pg_hba.conf
    dest: "/etc/postgresql/9.5/main/pg_hba.conf"
  become: yes
  register: pg_hba_changed

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
  when: pg_hba_changed|succeeded