---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: launch instance
      ec2:
        region: "{{ instance_region }}"
        instance_type: "{{ instance_type }}"
        image: "{{ instance_ami }}"
        wait: yes
        key_name: "{{ instance_name }}-key"
        group: "{{ instance_name }}-sg"
      register: ec2

    - name: associate new EIP with new instance
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item }}"
      with_items: "{{ ec2.instance_ids }}"