---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    sgname: "{{ security_group_name }}-sg"
  tasks:
    - name: create security group
      ec2_group:
        region: "{{ instance_region }}"
        name: "{{ sgname }}" 
        description: "security group for {{ security_group_name }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0