default: &default
  adapter: postgresql
  username: "{{ postgresql_user }}"
  password: "{{ postgresql_password }}"
  host: localhost

production:
  <<: *default
  database: "{{ instance_name }}-production"