default: &default
  adapter: postgresql
  username: "{{ postgresql_user }}"
  password: "{{ postgresql_password }}"
  host: localhost

# staging:
#   <<: *default
#   database: "{{ instance_name }}-staging"

production:
  <<: *default
  database: "{{ instance_name }}-production"